// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhykjbefaojfjwyauogc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoeWtqYmVmYW9qZmp3eWF1b2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTU2NTMsImV4cCI6MjA3MDQ3MTY1M30.PkjhntpOBdiDnRPBflSYMnd0zbNwpfXBu-g3AFsiTA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});